# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75d6105d7be28380952e202fefb63009bc6a1e04bfa643f94c306cf7ed17b6c6293b6c9c3f3bc5e944c5df3cfbe548dcd2abda3dac6e0236f4d1f3e954e9c0a9

test:
  secret_key_base: 42709b6aee31911ca651b795e7e8c8d3599c9dec2bd754f302f7f5744e11fdea0c012597c0ddecf0460705bcf59f0e9d71338e61f3ca3703202780dc869ea47e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
